<?php

namespace app\modules\admin;

use yii\base\Action;
use yii\base\ActionEvent;
use Yii;
use yii\helpers\Url;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'app\modules\admin\controllers';

    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }

    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
            Yii::$app->getResponse()->redirect(Url::to('/site/login'), 302);
        }
        return \yii\base\Module::beforeAction($action); // TODO: Change the autogenerated stub
    }


}
